-- Main workflow configuration table
CREATE TABLE APPROVAL_WORKFLOW_CONFIG (
    CONFIG_ID           VARCHAR2(50)    PRIMARY KEY,
    FUNCTION_CODE       VARCHAR2(50)    NOT NULL,
    TASK_CODE           VARCHAR2(50)    NOT NULL,
    CONFIG_JSON         CLOB            CHECK (CONFIG_JSON IS JSON),
    APPROVAL_TYPE       VARCHAR2(20)    DEFAULT 'STANDARD' CHECK (APPROVAL_TYPE IN ('STANDARD', 'FIELD_BASED', 'HYBRID')),
    IS_ACTIVE           CHAR(1)         DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y', 'N')),
    CREATED_ON          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(100)   NOT NULL,
    UPDATED_ON          TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_BY          VARCHAR2(100),
    
    CONSTRAINT UNQ_FUNC_TASK UNIQUE (FUNCTION_CODE, TASK_CODE)
);

-- Table to track field metadata for validation
CREATE TABLE APPROVAL_FIELD_METADATA (
    FIELD_CODE          VARCHAR2(50)    PRIMARY KEY,
    FIELD_NAME          VARCHAR2(200)   NOT NULL,
    FIELD_TYPE          VARCHAR2(20)    CHECK (FIELD_TYPE IN ('TEXT', 'NUMBER', 'DATE', 'DROPDOWN', 'BOOLEAN')),
    IS_CONDITIONAL      CHAR(1)         DEFAULT 'N' CHECK (IS_CONDITIONAL IN ('Y', 'N')),
    ALLOWED_OPERATORS   VARCHAR2(500),  -- JSON array of allowed operators
    CREATED_ON          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(100)   NOT NULL
);

-- Index for better performance
CREATE INDEX IDX_WORKFLOW_FUNC_TASK ON APPROVAL_WORKFLOW_CONFIG(FUNCTION_CODE, TASK_CODE);
