-- MAIN TABLE: APPROVAL_USER_GROUPS
CREATE TABLE APPROVAL_USER_GROUPS (
    GROUP_ID        VARCHAR2(50)    PRIMARY KEY,
    GROUP_NAME      VARCHAR2(200)   NOT NULL,
    STATUS          VARCHAR2(20)    DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED')),
    EFFECTIVE_START_DATE DATE        DEFAULT SYSDATE,
    EFFECTIVE_END_DATE   DATE,
    CREATED_ON      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(100)   NOT NULL,
    UPDATED_ON      TIMESTAMP       DEFAULT SYSTIMESTAMP,
    UPDATED_BY      VARCHAR2(100),
    DESCRIPTION     VARCHAR2(500),
    IS_DELETED      CHAR(1)         DEFAULT 'N' CHECK (IS_DELETED IN ('Y', 'N')),
    
    -- Constraints
    CONSTRAINT CHK_EFFECTIVE_DATES CHECK (EFFECTIVE_END_DATE IS NULL OR EFFECTIVE_END_DATE >= EFFECTIVE_START_DATE)
);